// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByk8OvE4KmJuu5VSaGuVSLEaUmanRa3Is',
    appId: '1:1051887840961:web:dae4bf3175dfd228d3ae40',
    messagingSenderId: '1051887840961',
    projectId: 'prism-dc2af',
    authDomain: 'prism-dc2af.firebaseapp.com',
    storageBucket: 'prism-dc2af.firebasestorage.app',
    measurementId: 'G-9W80PJP5TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ3FsDuJp1ieMLZBiBA5tRkMpspx0aG_c',
    appId: '1:1051887840961:android:d31ef96b7542d641d3ae40',
    messagingSenderId: '1051887840961',
    projectId: 'prism-dc2af',
    storageBucket: 'prism-dc2af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUjEVGx9x5dy-EoZ6u84HSjpYAUJjYd6k',
    appId: '1:1051887840961:ios:17ff32c9b6409cb3d3ae40',
    messagingSenderId: '1051887840961',
    projectId: 'prism-dc2af',
    storageBucket: 'prism-dc2af.firebasestorage.app',
    iosBundleId: 'com.example.prism',
  );
}
